server.port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username:  ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/JavaMicroAuthDB
  jpa:
    hibernate:
      ddl-auto: update

authservice:
  secrets:
    key: ${JAVA_SECRETKEY}
    issuer: ${JAVA_ISSUER}
    exDate: 300000




#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username:  postgres
#    password: 123456789
#    url: jdbc:postgresql://localhost:5432/JavaMicroAuthDB
#  jpa:
#    hibernate:
#      ddl-auto: update


#authservice:
#  secrets:
#    key: "123456789Abc"
#    issuer: "KurumAdi"
#    exDate:  1000L * 60 * 5


#spring:
#  datasource:
#    url: jdbc:h2:mem:mydemodb
#    username: sa
#    password:
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true