server.port: 8080

#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: 123456789
#    url: jdbc:postgresql://localhost:5432/mydemodb
#  jpa:
#    hibernate:
#      ddl-auto: update

spring:
  datasource:
    url: jdbc:h2:mem:mydemodb
    username: sa
    password:
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true