server.port: 9090

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username:  ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/JavaMicroAuthDB
  jpa:
    hibernate:
      ddl-auto: update

authservice:
  secrets:
    key: ${JAVA_SECRETKEY}
    issuer: ${JAVA_ISSUER}
    exDate: 300000